services:
  proxy:
    image: envoyproxy/envoy-dev:latest
    command: ["--log-level", "info", "-c", "/etc/envoy.yaml"]
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    ports:
      - 10000:10000 # httpbin listener
      - 9901:9901 # admin server
  processor:
    build:
      context: ./
      args:
        - GEOIP_CDN_ENDPOINT=${GEOIP_CDN_ENDPOINT}
    ports:
      - 8000:8000 # grpc server
    environment:
      ADDR: processor:8000
      BLOCKED_COUNTRY_CODES: ${BLOCKED_COUNTRY_CODES:-US}
  httpbin:
    image: kennethreitz/httpbin
